--DROP DATABASE IF EXISTS GamePPT
GO
CREATE DATABASE GamePPT
GO
USE GamePPT
GO
CREATE TABLE Batalla(
ID_Batalla INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Nombre NVARCHAR(200),
FechaInicio DATETIME DEFAULT(GETDATE()),
FechaFin DATETIME
)
GO
CREATE TABLE Jugador(
ID_Jugador INT PRIMARY KEY IDENTITY(100,1)NOT NULL,
Nombre NVARCHAR(100)
)
GO
CREATE TABLE JugadorBatalla(
ID_JugadorBatalla INT PRIMARY KEY IDENTITY(200,1)NOT NULL,
FK_ID_Batalla INT FOREIGN KEY REFERENCES Batalla(ID_Batalla)NOT NULL,
FK_ID_Jugador INT FOREIGN KEY REFERENCES Jugador(ID_Jugador)NOT NULL,
Gadador BIT
)
GO
CREATE TABLE Ronda(
ID_Ronda INT PRIMARY KEY IDENTITY(300,1) NOT NULL,
Nombre NVARCHAR(200)
)
GO
CREATE TABLE ResultadoBatallaRonda(
ID_ResultadoBatallaRonda INT PRIMARY KEY IDENTITY(400,1) NOT NULL,
Nombre NVARCHAR(200)
)
GO
CREATE TABLE Movimiento(
ID_Movimiento INT PRIMARY KEY IDENTITY(500,1) NOT NULL,
Nombre NVARCHAR(200)
)
GO
CREATE TABLE JugadorBatallaRonda(
ID_JugadorBatallaRonda INT PRIMARY KEY IDENTITY(600,1) NOT NULL,
FK_ID_JugadorBatalla INT FOREIGN KEY REFERENCES JugadorBatalla(ID_JugadorBatalla) NOT NULL,
FK_ID_Ronda INT FOREIGN KEY REFERENCES Ronda(ID_Ronda) NOT NULL,
FK_ID_ResultadoBatallaRonda INT FOREIGN KEY REFERENCES ResultadoBatallaRonda(ID_ResultadoBatallaRonda) NULL,
FK_ID_Movimiento INT FOREIGN KEY REFERENCES Movimiento(ID_Movimiento) NOT NULL
)
GO
-------------------------INSERTS---------------------------
INSERT INTO Movimiento VALUES('PIEDRA'),('PAPEL'),('TIJERA')
INSERT INTO ResultadoBatallaRonda VALUES('GANADOR'),('PERDEDOR'),('EMPATE')